Layout Pokemon's
denverden/pokemon pull request #2
Opened 2024-06-19 21:08 UTC by denverden

1. Screenshot:
![Screenshot](https://github.com/denverden/pokemon/assets/29141893/7ab88363-640c-4ab4-ac1e-f08d300d6b46)

2. Done 20.06.2024 / deadline 20.06.2024
`19 files in implementation. 7 of them are resources, pictures.`

- [x] change Listview
- [x] change layouts
- [x] added custum adapter

2024-06-20 05:22 UTC, pzinkevich42innowise requested changes

2024-06-20 05:22 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/pokemon/Adapter.kt
> +        val imageView: ImageView = view.findViewById(R.id.list_image)
подключил в проект биндинг, чтобы продолжать использовать findViewById

2024-06-20 05:22 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/pokemon/PokemonMockData.kt
> +    private val pokemons: HashMap<Int, Pokemon> = HashMap(listOf(
Зачем лишний раз оборачивать в HashMap, да ещё и точный тип указывать?

2024-06-20 05:22 UTC, pzinkevich42innowise commented on app/src/main/res/layout/activity_info.xml
> +    <LinearLayout
Зачем Linear внутри Constraint?

2024-06-20 05:22 UTC, pzinkevich42innowise commented on app/src/main/res/layout/activity_info.xml
> +        android:layout_marginTop="-35dp"
Отрицательные значения не принято использовать. Зачем они тебе?

2024-06-20 05:22 UTC, pzinkevich42innowise commented on app/src/main/res/layout/custom_card_view.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
А в чём смысл этого Constraint?

2024-06-20 08:33 UTC, denverden commented on app/src/main/res/layout/activity_info.xml
> +    <LinearLayout
Пока не совсеми элементами познакомился. Тут использовал по дизайну, чтобы сформировать что-то вроде списка, ну и графику в background положить. Linar запрещается внутри Constraint или просто не рекомендуется?

2024-06-20 08:49 UTC, denverden commented on app/src/main/java/com/example/pokemon/PokemonMockData.kt
> +    private val pokemons: HashMap<Int, Pokemon> = HashMap(listOf(
да возвращается Map, оборачивать не надо в HashMap. На лекции об этом говорилось. Перекочевало из старой реализации.

2024-06-20 08:53 UTC, denverden commented on app/src/main/res/layout/activity_info.xml
> +        android:layout_marginTop="-35dp"
использовал чтобы изображение немного наложилось на область с информацией. Так как изображения с альфа-каналом. Возможно для такого правильно использовать FrameLayout (не все элементы изучил).

2024-06-20 08:55 UTC, denverden commented on app/src/main/res/layout/custom_card_view.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
нет смысла. Даже как-то не задумался, он создался автоматически при создании layout. Так и стал в него все реализовывать. Удалил.

2024-06-21 04:50 UTC, pzinkevich42innowise commented on app/src/main/res/layout/activity_info.xml
> +    <LinearLayout
Нет, просто всю вёрстку можно сделать и так на основе Constraint, но если тебе так проще - ок

2024-06-21 04:51 UTC, pzinkevich42innowise approved these changes

2024-06-21 05:46 UTC, merged