Release/v1.0.0
denverden/pokemon pull request #6
Opened 2024-06-30 20:37 UTC by denverden

1. Screenshot:
![Screenshot](https://github.com/denverden/pokemon/assets/29141893/8be78a08-4c52-4db2-ac4c-1f1adfcb0819)

2. Done 30.06.2024 / deadline 01.07.2024

- [x] main activity displays a list of Pokemon
- [x] activity information displays a specific Pokemon
- [x] information activities return to main activity

2024-06-30 21:41 UTC, pzinkevich42innowise requested changes

2024-06-30 21:41 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/pokemon/MainActivity.kt
> +        recyclerView.layoutManager = LinearLayoutManager(this)
Это в xml вынести

2024-07-04 10:26 UTC, pzinkevich42innowise requested changes

2024-07-04 10:26 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/pokemon/MainActivity.kt
> +            listView.layoutManager = LinearLayoutManager(this@MainActivity)
Вынести в разметку

2024-07-04 12:44 UTC, denverden commented on app/src/main/java/com/example/pokemon/MainActivity.kt
> +            listView.layoutManager = LinearLayoutManager(this@MainActivity)
Извиняюсь, не сразу понял что нужно было сделать) Исправил.

2024-07-06 12:39 UTC, pzinkevich42innowise approved these changes

2024-07-07 10:32 UTC, merged